#############################################################################
# Makefile for building: Mine
# Generated by qmake (2.01a) (Qt 4.8.2) on: ?? 3? 8 21:53:16 2014
# Project:  Mine.pro
# Template: app
# Command: /usr/bin/qmake -o Makefile Mine.pro
#############################################################################

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_WEBKIT -DQT_NO_DEBUG -DQT_GUI_LIB -DQT_CORE_LIB -DQT_SHARED
CFLAGS        = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I/usr/share/qt4/mkspecs/linux-g++ -I. -I/usr/include/qt4/QtCore -I/usr/include/qt4/QtGui -I/usr/include/qt4 -I. -I.
LINK          = g++
LFLAGS        = -Wl,-O1
LIBS          = $(SUBLIBS)  -L/usr/lib/mipsel-linux-gnu -lQtGui -lQtCore -lpthread 
AR            = ar cqs
RANLIB        = 
QMAKE         = /usr/bin/qmake
TAR           = tar -cf
COMPRESS      = gzip -9f
COPY          = cp -f
SED           = sed
COPY_FILE     = $(COPY)
COPY_DIR      = $(COPY) -r
STRIP         = strip
INSTALL_FILE  = install -m 644 -p
INSTALL_DIR   = $(COPY_DIR)
INSTALL_PROGRAM = install -m 755 -p
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = config.cpp \
		main.cpp \
		mainwindow.cpp \
		minefield.cpp \
		minelogical.cpp \
		privatedialog.cpp moc_mainwindow.cpp \
		moc_minefield.cpp \
		moc_privatedialog.cpp \
		qrc_mine.cpp
OBJECTS       = config.o \
		main.o \
		mainwindow.o \
		minefield.o \
		minelogical.o \
		privatedialog.o \
		moc_mainwindow.o \
		moc_minefield.o \
		moc_privatedialog.o \
		qrc_mine.o
DIST          = /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		Mine.pro
QMAKE_TARGET  = Mine
DESTDIR       = 
TARGET        = Mine

first: all
####### Implicit rules

.SUFFIXES: .o .c .cpp .cc .cxx .C

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cc.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.C.o:
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o "$@" "$<"

.c.o:
	$(CC) -c $(CFLAGS) $(INCPATH) -o "$@" "$<"

####### Build rules

all: Makefile $(TARGET)

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: Mine.pro  /usr/share/qt4/mkspecs/linux-g++/qmake.conf /usr/share/qt4/mkspecs/common/unix.conf \
		/usr/share/qt4/mkspecs/common/linux.conf \
		/usr/share/qt4/mkspecs/common/gcc-base.conf \
		/usr/share/qt4/mkspecs/common/gcc-base-unix.conf \
		/usr/share/qt4/mkspecs/common/g++-base.conf \
		/usr/share/qt4/mkspecs/common/g++-unix.conf \
		/usr/share/qt4/mkspecs/qconfig.pri \
		/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri \
		/usr/share/qt4/mkspecs/features/qt_functions.prf \
		/usr/share/qt4/mkspecs/features/qt_config.prf \
		/usr/share/qt4/mkspecs/features/exclusive_builds.prf \
		/usr/share/qt4/mkspecs/features/default_pre.prf \
		/usr/share/qt4/mkspecs/features/release.prf \
		/usr/share/qt4/mkspecs/features/default_post.prf \
		/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf \
		/usr/share/qt4/mkspecs/features/warn_on.prf \
		/usr/share/qt4/mkspecs/features/qt.prf \
		/usr/share/qt4/mkspecs/features/unix/thread.prf \
		/usr/share/qt4/mkspecs/features/moc.prf \
		/usr/share/qt4/mkspecs/features/resources.prf \
		/usr/share/qt4/mkspecs/features/uic.prf \
		/usr/share/qt4/mkspecs/features/yacc.prf \
		/usr/share/qt4/mkspecs/features/lex.prf \
		/usr/share/qt4/mkspecs/features/include_source_dir.prf \
		/usr/lib/mipsel-linux-gnu/libQtGui.prl \
		/usr/lib/mipsel-linux-gnu/libQtCore.prl
	$(QMAKE) -o Makefile Mine.pro
/usr/share/qt4/mkspecs/common/unix.conf:
/usr/share/qt4/mkspecs/common/linux.conf:
/usr/share/qt4/mkspecs/common/gcc-base.conf:
/usr/share/qt4/mkspecs/common/gcc-base-unix.conf:
/usr/share/qt4/mkspecs/common/g++-base.conf:
/usr/share/qt4/mkspecs/common/g++-unix.conf:
/usr/share/qt4/mkspecs/qconfig.pri:
/usr/share/qt4/mkspecs/modules/qt_webkit_version.pri:
/usr/share/qt4/mkspecs/features/qt_functions.prf:
/usr/share/qt4/mkspecs/features/qt_config.prf:
/usr/share/qt4/mkspecs/features/exclusive_builds.prf:
/usr/share/qt4/mkspecs/features/default_pre.prf:
/usr/share/qt4/mkspecs/features/release.prf:
/usr/share/qt4/mkspecs/features/default_post.prf:
/usr/share/qt4/mkspecs/features/unix/gdb_dwarf_index.prf:
/usr/share/qt4/mkspecs/features/warn_on.prf:
/usr/share/qt4/mkspecs/features/qt.prf:
/usr/share/qt4/mkspecs/features/unix/thread.prf:
/usr/share/qt4/mkspecs/features/moc.prf:
/usr/share/qt4/mkspecs/features/resources.prf:
/usr/share/qt4/mkspecs/features/uic.prf:
/usr/share/qt4/mkspecs/features/yacc.prf:
/usr/share/qt4/mkspecs/features/lex.prf:
/usr/share/qt4/mkspecs/features/include_source_dir.prf:
/usr/lib/mipsel-linux-gnu/libQtGui.prl:
/usr/lib/mipsel-linux-gnu/libQtCore.prl:
qmake:  FORCE
	@$(QMAKE) -o Makefile Mine.pro

dist: 
	@$(CHK_DIR_EXISTS) .tmp/Mine1.0.0 || $(MKDIR) .tmp/Mine1.0.0 
	$(COPY_FILE) --parents $(SOURCES) $(DIST) .tmp/Mine1.0.0/ && $(COPY_FILE) --parents config.h mainwindow.h minefield.h minelogical.h privatedialog.h .tmp/Mine1.0.0/ && $(COPY_FILE) --parents mine.qrc .tmp/Mine1.0.0/ && $(COPY_FILE) --parents config.cpp main.cpp mainwindow.cpp minefield.cpp minelogical.cpp privatedialog.cpp .tmp/Mine1.0.0/ && (cd `dirname .tmp/Mine1.0.0` && $(TAR) Mine1.0.0.tar Mine1.0.0 && $(COMPRESS) Mine1.0.0.tar) && $(MOVE) `dirname .tmp/Mine1.0.0`/Mine1.0.0.tar.gz . && $(DEL_FILE) -r .tmp/Mine1.0.0


clean:compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


####### Sub-libraries

distclean: clean
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) Makefile


check: first

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

compiler_moc_header_make_all: moc_mainwindow.cpp moc_minefield.cpp moc_privatedialog.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_mainwindow.cpp moc_minefield.cpp moc_privatedialog.cpp
moc_mainwindow.cpp: mainwindow.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) mainwindow.h -o moc_mainwindow.cpp

moc_minefield.cpp: minelogical.h \
		config.h \
		minefield.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) minefield.h -o moc_minefield.cpp

moc_privatedialog.cpp: privatedialog.h
	/usr/bin/moc-qt4 $(DEFINES) $(INCPATH) privatedialog.h -o moc_privatedialog.cpp

compiler_rcc_make_all: qrc_mine.cpp
compiler_rcc_clean:
	-$(DEL_FILE) qrc_mine.cpp
qrc_mine.cpp: mine.qrc \
		images/errflag.svg \
		images/mine.png \
		images/flag.svg \
		images/bang.svg \
		images/win.png \
		images/failed.png
	/usr/bin/rcc -name mine mine.qrc -o qrc_mine.cpp

compiler_image_collection_make_all: qmake_image_collection.cpp
compiler_image_collection_clean:
	-$(DEL_FILE) qmake_image_collection.cpp
compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_header_clean compiler_rcc_clean 

####### Compile

config.o: config.cpp config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o config.o config.cpp

main.o: main.cpp mainwindow.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o main.cpp

mainwindow.o: mainwindow.cpp mainwindow.h \
		minefield.h \
		minelogical.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o mainwindow.o mainwindow.cpp

minefield.o: minefield.cpp minefield.h \
		minelogical.h \
		config.h \
		privatedialog.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minefield.o minefield.cpp

minelogical.o: minelogical.cpp minelogical.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o minelogical.o minelogical.cpp

privatedialog.o: privatedialog.cpp privatedialog.h \
		config.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o privatedialog.o privatedialog.cpp

moc_mainwindow.o: moc_mainwindow.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_mainwindow.o moc_mainwindow.cpp

moc_minefield.o: moc_minefield.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_minefield.o moc_minefield.cpp

moc_privatedialog.o: moc_privatedialog.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_privatedialog.o moc_privatedialog.cpp

qrc_mine.o: qrc_mine.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o qrc_mine.o qrc_mine.cpp

####### Install

install:   FORCE

uninstall:   FORCE

FORCE:

